#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on

ip_addresses=$(ip -o -4 addr show scope global | awk '{split($4, a, "/"); print a[1]}')
echo "$ip_addresses"

